name: Create Release for UptickSDK

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  create_release:
    runs-on: warp-ubuntu-2204-x64-4x

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip up the XCFramework
      run: zip -r UptickSDK.xcframework.zip UptickSDK.xcframework

    - name: Log GitHub Context
      run: |
        echo "Ref Name: ${{ github.ref_name }}"
        echo "Commit Message: ${{ github.event.head_commit.message }}"
        echo "GitHub Context:"
        echo "${{ toJson(github) }}"

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.PPX_DIGITAL_ACTIONS_PAT }}
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{  github.ref_name }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
        make_latest: true
        files: 'UptickSDK.xcframework.zip'
        fail_on_unmatched_files: false

  publish_to_cocoapods:
    runs-on: macos-latest
    needs: [create_release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract Version from Podspec
      id: version_extractor
      run: |
        VERSION=$(grep -E 'spec.version\s*=\s*"[^"]*"' UptickSDK.podspec | sed -E 's/.*spec.version\s*=\s*"([^"]*)".*/\1/')
        echo "Current version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
 
    - name: Setup Ruby and Cocoapods
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
 
    - name: Validate Podspec
      run: pod lib lint --allow-warnings --verbose
 
    - name: Publish to Cocoapods Trunk
      run: pod trunk push UptickSDK.podspec --allow-warnings --verbose
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
